### ISSUE TITLE
test failed 'got expected data structure'

### ISSUE THREAD

**Issue by electricface** [tony-o/perl6-data-dump#3]
```
==> Fetching Data::Dump
==> Building Data::Dump
==> Testing Data::Dump
t/00-use.t .... ok
t/01-hash.t ... ok

# Failed test 'got expected data structure'
# at t/02-obj.t line 21
E :: (
  $!private => 5.Int,
  $!public => (Any),

  method e () returns Int {...},
  method public () returns Mu {...},
  method r (Str $a) returns Mu {...},
  method s ($b, :$named = 5) returns Mu {...},
)
  in block <unit> at t/02-obj.t:21

# Looks like you failed 1 test of 1
t/02-obj.t ....
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/03-array.t .. ok

Test Summary Report
-------------------
t/02-obj.t  (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=4, Tests=4,  5 wallclock secs ( 0.03 usr  0.01 sys +  4.81 cusr  0.29 csys =  5.14 CPU)
Result: FAIL
test stage failed for Data::Dump: Tests failed
  in method throw at /home/git-repo/perl6_install/share/perl6/runtime/CORE.setting.moarvm:1
  in method install at /home/git-repo/perl6_install/share/perl6/site/lib/Panda.pm:142
  in method resolve at /home/git-repo/perl6_install/share/perl6/site/lib/Panda.pm:219
  in sub MAIN at /home/git-repo/perl6_install/share/perl6/site/bin/panda:18
  in block <unit> at /home/git-repo/perl6_install/share/perl6/site/bin/panda:95


Failure Summary
----------------
Data::Dump(
        *test stage failed for Data::Dump: Tests failed)

```

perl6 version 2015.07.1-849-g296824d built on MoarVM version 2015.08-32-g8a56510

**Comment by stmuk** [comment]
FIxed by https://github.com/tony-o/perl6-data-dump/pull/4

**Comment by stmuk** [comment]
Why did you close this rather than accept the PR? The issue still exists.

% /opt/rakudo-star-2015.09-RC0/bin/panda install Data::Dump
==> Fetching Data::Dump
==> Building Data::Dump
==> Testing Data::Dump
t/00-use.t .... ok
t/01-hash.t ... ok

# Failed test 'got expected data structure'

# at t/02-obj.t line 21

E :: (
  $!private => 5.Int,
  $!public => (Any),

  method e () returns Int {...},
  method public () returns Mu {...},
  method r (Str $a) returns Mu {...},
  method s ($b, :$named = 5) returns Mu {...},
)
  in block <unit> at t/02-obj.t:21

# Looks like you failed 1 test of 1

t/02-obj.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

**Comment by tony-o** [comment]
@stmuk sorry - just merged #4.  I thought I'd already merged, thank you

**Comment by stmuk** [comment]
OK thanks!  Hopefully rakudo will stablise soon and this tweaking be a thing of the past!

**Comment by tony-o** [comment]
I'm really hoping they fix the CURLI implementation.  @ugexe has already given them the code to do it, they're just dragging their feet.
